package eventBus;

public enum Topic
{
  CHAT_EVENT,
  CHAT_COMMAND,
  CHAT_SERVICE_EVENT,
  CHAT_SERVICE_COMMAND,
  SESSION_SERVICE_EVENT,
  SESSION_SERVICE_COMMAND,
  SESSION_COMMAND,
  SESSION_EVENT,
  WORKSPACES_SERVICE_EVENT,
  WORKSPACES_SERVICE_COMMAND,
  WORKSPACES_COMMAND,
  WORKSPACES_EVENT
}
